services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Avro\CaseBundle\Twig\Extension\CaseExtension:
        tags:
            - { name: twig.extension }
